import type { z } from "zod";
import { WorkbenchOpenTarget } from "../app/domain.js";
import { SessionBinding } from "./binding.js";
import {
  BrowserClickParams,
  BrowserClickResult,
  BrowserEvalParams,
  BrowserEvalResult,
  BrowserOpenParams,
  BrowserOpenResult,
  BrowserReadParams,
  BrowserReadResult,
  BrowserScrollParams,
  BrowserScrollResult,
  BrowserTypeParams,
  BrowserTypeResult,
  ContextParams,
  ContextResult,
  GuideParams,
  GuideResult,
  PreviewTarget,
  TeamListParams,
  TeamListResult,
  TerminalReadParams,
  TerminalReadResult,
  TerminalRunParams,
  TerminalRunResult,
  TerminalWriteParams,
  TerminalWriteResult,
  ThreadListItem,
  ThreadListParams,
  ThreadListResult,
  ThreadPostParams,
  ThreadPostResult,
  ThreadPrsParams,
  ThreadPrsResult,
  ThreadReadParams,
  ThreadReadResult,
  ThreadSearchParams,
  ThreadSearchResult,
  ThreadSetTitleParams,
  ThreadSetTitleResult,
  WorkbenchOpenResult,
  WorkbenchPreviewsParams,
  WorkbenchPreviewsResult,
} from "./tools.js";
import {
  ViewerActivity,
  ViewerBrowserInput,
  ViewerBrowserNavigate,
  ViewerBrowserResize,
  ViewerClientMsg,
  ViewerFrame,
  ViewerHello,
  ViewerPage,
  ViewerPreviews,
  ViewerServerMsg,
  ViewerTerm,
  ViewerTermControl,
  ViewerTermInput,
  ViewerTermRelease,
  ViewerTermResize,
  ViewerUrl,
} from "./viewer.js";

/**
 * Harness-protocol schema registry — consumed by
 * `packages/contracts/scripts/gen-schemas.ts` into
 * `generated/harness-protocol.schema.json`.
 */
export const harnessProtocolSchemas = {
  BrowserOpenParams,
  BrowserOpenResult,
  BrowserClickParams,
  BrowserClickResult,
  BrowserTypeParams,
  BrowserTypeResult,
  BrowserReadParams,
  BrowserReadResult,
  BrowserScrollParams,
  BrowserScrollResult,
  BrowserEvalParams,
  BrowserEvalResult,
  TerminalRunParams,
  TerminalRunResult,
  TerminalWriteParams,
  TerminalWriteResult,
  TerminalReadParams,
  TerminalReadResult,
  PreviewTarget,
  WorkbenchPreviewsParams,
  WorkbenchPreviewsResult,
  WorkbenchOpenTarget,
  WorkbenchOpenResult,
  ThreadPostParams,
  ThreadPostResult,
  ThreadReadParams,
  ThreadReadResult,
  ThreadListParams,
  ThreadListItem,
  ThreadListResult,
  ThreadSearchParams,
  ThreadSearchResult,
  ThreadSetTitleParams,
  ThreadSetTitleResult,
  ThreadPrsParams,
  ThreadPrsResult,
  ContextParams,
  ContextResult,
  GuideParams,
  GuideResult,
  TeamListParams,
  TeamListResult,
  SessionBinding,
  ViewerHello,
  ViewerFrame,
  ViewerTerm,
  ViewerUrl,
  ViewerPreviews,
  ViewerPage,
  ViewerTermControl,
  ViewerActivity,
  ViewerServerMsg,
  ViewerTermInput,
  ViewerTermResize,
  ViewerBrowserInput,
  ViewerBrowserNavigate,
  ViewerBrowserResize,
  ViewerTermRelease,
  ViewerClientMsg,
} satisfies Record<string, z.ZodType>;

export const harnessProtocol = {
  name: "harness",
  version: 1,
  schemas: harnessProtocolSchemas,
};
