import type { z } from "zod";
import {
  AppPostMessageParams,
  AppPostMessageResult,
  AppReadConversationParams,
  AppReadConversationResult,
  BrowserClickParams,
  BrowserClickResult,
  BrowserEvalParams,
  BrowserEvalResult,
  BrowserOpenParams,
  BrowserOpenResult,
  BrowserReadParams,
  BrowserReadResult,
  BrowserScrollParams,
  BrowserScrollResult,
  BrowserTypeParams,
  BrowserTypeResult,
  PreviewsListParams,
  PreviewsListResult,
  PreviewTarget,
  TerminalReadParams,
  TerminalReadResult,
  TerminalRunParams,
  TerminalRunResult,
  TerminalWriteParams,
  TerminalWriteResult,
} from "./tools.js";
import {
  ViewerActivity,
  ViewerBrowserInput,
  ViewerBrowserNavigate,
  ViewerClientMsg,
  ViewerFrame,
  ViewerHello,
  ViewerPreviews,
  ViewerServerMsg,
  ViewerTerm,
  ViewerTermInput,
  ViewerTermResize,
  ViewerUrl,
} from "./viewer.js";

/**
 * Harness-protocol schema registry — consumed by
 * `packages/contracts/scripts/gen-schemas.ts` into
 * `generated/harness-protocol.schema.json`.
 */
export const harnessProtocolSchemas = {
  BrowserOpenParams,
  BrowserOpenResult,
  BrowserClickParams,
  BrowserClickResult,
  BrowserTypeParams,
  BrowserTypeResult,
  BrowserReadParams,
  BrowserReadResult,
  BrowserScrollParams,
  BrowserScrollResult,
  BrowserEvalParams,
  BrowserEvalResult,
  TerminalRunParams,
  TerminalRunResult,
  TerminalWriteParams,
  TerminalWriteResult,
  TerminalReadParams,
  TerminalReadResult,
  PreviewTarget,
  PreviewsListParams,
  PreviewsListResult,
  AppPostMessageParams,
  AppPostMessageResult,
  AppReadConversationParams,
  AppReadConversationResult,
  ViewerHello,
  ViewerFrame,
  ViewerTerm,
  ViewerUrl,
  ViewerPreviews,
  ViewerActivity,
  ViewerServerMsg,
  ViewerTermInput,
  ViewerTermResize,
  ViewerBrowserInput,
  ViewerBrowserNavigate,
  ViewerClientMsg,
} satisfies Record<string, z.ZodType>;

export const harnessProtocol = {
  name: "harness",
  version: 1,
  schemas: harnessProtocolSchemas,
};
