import { RelayClient } from "@lilos/client-runtime";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
const state = JSON.parse(readFileSync(join(homedir(), ".lilos", "drive-turn.json"), "utf8"));
const token = readFileSync(join(homedir(), ".lilos", "relay-token"), "utf8").trim();
const c = new RelayClient({ url: "ws://127.0.0.1:4577/ws", token, client: { name: "dbg", version: "0" } });
await c.connect();
const r = await c.request("messages.post", { channelId: state.channelId, conversationId: state.conversationId, text: "Add a footer to the page", authorKind: "user" });
console.log(JSON.stringify(r));
c.close();
