import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { promisify } from "node:util";
import type { UpdateRelease } from "@lilos/contracts/app";
import type { UpdatePaths } from "./state";

const execFileP = promisify(execFile);

/**
 * Download + verify + unpack a release into `staging/`. Returns the staged
 * .app path. Throws on any integrity problem — nothing half-staged survives
 * because staging/ is wiped at entry and the payload is only unpacked after
 * the checksum matches.
 */
export async function stageRelease(
  release: UpdateRelease,
  paths: UpdatePaths,
  fetchImpl: typeof fetch = fetch,
): Promise<string> {
  mkdirSync(paths.downloads, { recursive: true });
  const zipPath = join(paths.downloads, `lilos-${release.build}.zip`);
  const res = await fetchImpl(release.url);
  if (!res.ok)
    throw new Error(`update download ${release.url}: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const sha = createHash("sha256").update(buf).digest("hex");
  if (sha !== release.sha256.toLowerCase()) {
    throw new Error(
      `update checksum mismatch: got ${sha}, want ${release.sha256}`,
    );
  }
  writeFileSync(zipPath, buf);

  rmSync(paths.stagingDir, { recursive: true, force: true });
  mkdirSync(paths.stagingDir, { recursive: true });
  await execFileP("ditto", ["-x", "-k", zipPath, paths.stagingDir]);
  // Zip modes can't be trusted end to end (feed producer → http → extractor).
  // Every bundle entry point lives under Contents/MacOS or is the crashpad
  // helper — restore the exec bit explicitly.
  await execFileP("find", [
    paths.stagingDir,
    "-type",
    "f",
    "(",
    "-path",
    "*/MacOS/*",
    "-o",
    "-name",
    "chrome_crashpad_handler",
    ")",
    "-exec",
    "chmod",
    "755",
    "{}",
    "+",
  ]);
  const apps = readdirSync(paths.stagingDir).filter((f) => f.endsWith(".app"));
  if (apps.length !== 1) {
    throw new Error(`update payload has ${apps.length} .app bundles, want 1`);
  }
  return join(paths.stagingDir, apps[0]);
}

export interface ApplyScriptOpts {
  installPath: string;
  stagedApp: string;
  rollbackApp: string;
  bootOkFile: string;
  statusFile: string;
  pendingFile: string;
  oldPid: number;
  logFile: string;
  junkDir?: string;
  bootWaitSeconds?: number;
}

/**
 * The detached applier: runs after the app quits, swaps the staged bundle
 * into the install path, relaunches, and waits for the new build to write
 * `boot-ok` (which it does only after re-registering services and passing
 * the relay version handshake). No boot-ok in time → kill, restore, relaunch
 * the old build — that is the AC-4 rollback.
 *
 * Rendered as one self-contained bash file so the update survives the
 * quitting app — no dependency on the app's own files mid-swap.
 */
export function renderApplyScript(o: ApplyScriptOpts): string {
  const wait = o.bootWaitSeconds ?? 120;
  const junk = o.junkDir ?? join(o.rollbackApp, "..", "..", "junk");
  const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  return `#!/bin/bash
# LilOS update applier — generated by the app at stage time; delete-safe.
set -u
APP=${q(o.installPath)}
STAGED=${q(o.stagedApp)}
ROLLBACK=${q(o.rollbackApp)}
JUNK=${q(junk)}
BOOT_OK=${q(o.bootOkFile)}
STATUS=${q(o.statusFile)}
LOG=${q(o.logFile)}
OLDPID=${o.oldPid}
WAIT=${wait}

# The app rewrites this script file on the next update — a running applier
# could be reading the old copy at any offset, so every error and trace goes
# to the log and the applier runs a per-build copy (see checkForUpdate).
exec >>"$LOG" 2>&1
[ "$LILOS_UPDATE_TRACE" = "1" ] && set -x
log() { echo "[$(date '+%H:%M:%S')] $*"; }
status() { printf '{"phase":"%s","detail":"%s","at":%s}\\n' "$1" "$2" "$(date +%s)000" > "$STATUS"; }

# One applier at a time (a second update tick can overlap stage+apply).
# mkdir is atomic; a lock older than 10 min is treated as stale/crashed.
LOCK="$(dirname "$LOG")/apply.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
  lockAge=$(( $(date +%s) - $(stat -f %m "$LOCK" 2>/dev/null || echo 0) ))
  if [ "$lockAge" -gt 600 ]; then
    rm -rf "$LOCK"
    mkdir "$LOCK" 2>/dev/null || exit 0
  else
    exit 0
  fi
fi
trap 'rm -rf "$LOCK"' EXIT

log "apply: waiting for old app (pid $OLDPID) to exit"
for i in $(seq 1 150); do
  kill -0 "$OLDPID" 2>/dev/null || break
  sleep 0.2
done

mkdir -p "$(dirname "$ROLLBACK")" "$JUNK"
rm -f "$BOOT_OK"
rm -rf "$ROLLBACK"

log "apply: park $APP -> $ROLLBACK"
if ! mv "$APP" "$ROLLBACK"; then
  status failed "cannot park the running app"
  exit 1
fi
log "apply: install $STAGED -> $APP"
if ! mv "$STAGED" "$APP"; then
  mv "$ROLLBACK" "$APP"
  status failed "cannot install the staged app"
  exit 1
fi

# Zip modes survive imperfectly end to end — restore exec bits on every
# bundle entry point and drop quarantine inherited from the download
# (same normalization Squirrel.mac does on extracted updates).
find "$APP" -type f -path "*/MacOS/*" -exec chmod 755 {} +
find "$APP" -type f -name chrome_crashpad_handler -exec chmod 755 {} +
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true
log "apply: normalized perms, staged $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP/Contents/Info.plist" 2>/dev/null || echo '?')"

log "apply: launching new build"
"$APP/Contents/MacOS/LilOS" >> "$LOG" 2>&1 &
NEW=$!
log "apply: new build pid $NEW"

ok=""
for i in $(seq 1 $((WAIT * 10))); do
  if [ -f "$BOOT_OK" ]; then ok=1; break; fi
  kill -0 "$NEW" 2>/dev/null || break
  sleep 0.1
done

if [ -n "$ok" ]; then
  log "apply: new build verified itself (boot-ok)"
  status updated ""
  exit 0
fi

log "apply: no boot-ok — killing new build and restoring old"
kill "$NEW" 2>/dev/null
sleep 0.5
kill -9 "$NEW" 2>/dev/null
mv "$APP" "$JUNK/LilOS-bad-$(date +%s).app" 2>/dev/null || rm -rf "$APP"
if ! mv "$ROLLBACK" "$APP"; then
  status failed "rollback failed — app left parked"
  exit 1
fi
find "$APP" -type f -path "*/MacOS/*" -exec chmod 755 {} +
find "$APP" -type f -name chrome_crashpad_handler -exec chmod 755 {} +
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true
log "apply: relaunching previous build"
"$APP/Contents/MacOS/LilOS" >> "$LOG" 2>&1 &
status rolled-back "previous version restored"
exit 0
`;
}

/** Write the applier to disk, ready to spawn detached. */
export function writeApplier(paths: UpdatePaths, script: string): string {
  mkdirSync(paths.root, { recursive: true });
  writeFileSync(paths.applyScript, script);
  chmodSync(paths.applyScript, 0o755);
  return paths.applyScript;
}
