import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { promisify } from "node:util";
import type { UpdateRelease } from "@lilos/contracts/app";
import type { UpdatePaths } from "./state";

const execFileP = promisify(execFile);

/**
 * Download + verify + unpack a release into `staging/`. Returns the staged
 * .app path. Throws on any integrity problem — nothing half-staged survives
 * because staging/ is wiped at entry and the payload is only unpacked after
 * the checksum matches.
 */
export async function stageRelease(
  release: UpdateRelease,
  paths: UpdatePaths,
  fetchImpl: typeof fetch = fetch,
): Promise<string> {
  mkdirSync(paths.downloads, { recursive: true });
  const zipPath = join(paths.downloads, `lilos-${release.build}.zip`);
  const res = await fetchImpl(release.url);
  if (!res.ok)
    throw new Error(`update download ${release.url}: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const sha = createHash("sha256").update(buf).digest("hex");
  if (sha !== release.sha256.toLowerCase()) {
    throw new Error(
      `update checksum mismatch: got ${sha}, want ${release.sha256}`,
    );
  }
  writeFileSync(zipPath, buf);

  rmSync(paths.stagingDir, { recursive: true, force: true });
  mkdirSync(paths.stagingDir, { recursive: true });
  await execFileP("ditto", ["-x", "-k", zipPath, paths.stagingDir]);
  const apps = readdirSync(paths.stagingDir).filter((f) => f.endsWith(".app"));
  if (apps.length !== 1) {
    throw new Error(`update payload has ${apps.length} .app bundles, want 1`);
  }
  return join(paths.stagingDir, apps[0]);
}

export interface ApplyScriptOpts {
  installPath: string;
  stagedApp: string;
  rollbackApp: string;
  bootOkFile: string;
  statusFile: string;
  pendingFile: string;
  oldPid: number;
  logFile: string;
  junkDir?: string;
  bootWaitSeconds?: number;
}

/**
 * The detached applier: runs after the app quits, swaps the staged bundle
 * into the install path, relaunches, and waits for the new build to write
 * `boot-ok` (which it does only after re-registering services and passing
 * the relay version handshake). No boot-ok in time → kill, restore, relaunch
 * the old build — that is the AC-4 rollback.
 *
 * Rendered as one self-contained bash file so the update survives the
 * quitting app — no dependency on the app's own files mid-swap.
 */
export function renderApplyScript(o: ApplyScriptOpts): string {
  const wait = o.bootWaitSeconds ?? 120;
  const junk = o.junkDir ?? join(o.rollbackApp, "..", "..", "junk");
  const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  return `#!/bin/bash
# LilOS update applier — generated by the app at stage time; delete-safe.
set -u
APP=${q(o.installPath)}
STAGED=${q(o.stagedApp)}
ROLLBACK=${q(o.rollbackApp)}
JUNK=${q(junk)}
BOOT_OK=${q(o.bootOkFile)}
STATUS=${q(o.statusFile)}
LOG=${q(o.logFile)}
OLDPID=${o.oldPid}
WAIT=${wait}

log() { echo "[$(date '+%H:%M:%S')] $*" >> "$LOG"; }
status() { printf '{"phase":"%s","detail":"%s","at":%s}\\n' "$1" "$2" "$(date +%s)000" > "$STATUS"; }

log "apply: waiting for old app (pid $OLDPID) to exit"
for i in $(seq 1 150); do
  kill -0 "$OLDPID" 2>/dev/null || break
  sleep 0.2
done

mkdir -p "$(dirname "$ROLLBACK")" "$JUNK"
rm -f "$BOOT_OK"

log "apply: park $APP -> $ROLLBACK"
if ! mv "$APP" "$ROLLBACK"; then
  status failed "cannot park the running app"
  exit 1
fi
log "apply: install $STAGED -> $APP"
if ! mv "$STAGED" "$APP"; then
  mv "$ROLLBACK" "$APP"
  status failed "cannot install the staged app"
  exit 1
fi

log "apply: launching new build"
"$APP/Contents/MacOS/LilOS" >> "$LOG" 2>&1 &
NEW=$!

ok=""
for i in $(seq 1 $((WAIT * 10))); do
  if [ -f "$BOOT_OK" ]; then ok=1; break; fi
  kill -0 "$NEW" 2>/dev/null || break
  sleep 0.1
done

if [ -n "$ok" ]; then
  log "apply: new build verified itself (boot-ok)"
  status updated ""
  exit 0
fi

log "apply: no boot-ok — killing new build and restoring old"
kill "$NEW" 2>/dev/null
sleep 0.5
kill -9 "$NEW" 2>/dev/null
mv "$APP" "$JUNK/LilOS-bad-$(date +%s).app" 2>/dev/null || rm -rf "$APP"
if ! mv "$ROLLBACK" "$APP"; then
  status failed "rollback failed — app left parked"
  exit 1
fi
"$APP/Contents/MacOS/LilOS" >> "$LOG" 2>&1 &
status rolled-back "previous version restored"
exit 0
`;
}

/** Write the applier to disk, ready to spawn detached. */
export function writeApplier(paths: UpdatePaths, script: string): string {
  mkdirSync(paths.root, { recursive: true });
  writeFileSync(paths.applyScript, script);
  chmodSync(paths.applyScript, 0o755);
  return paths.applyScript;
}
