import type { z } from "zod";
import { ChannelMessage } from "../index";
import {
  AppChannel,
  AppMessage,
  Ask,
  AskState,
  AuthorKind,
  ChannelKind,
  Conversation,
  ConversationState,
  Employee,
  EmployeeStatus,
  EngineHostState,
  EngineHostStatus,
  PendingTurn,
  RespondTo,
} from "./domain";
import { APP_PROTOCOL_VERSION } from "./version";
import {
  AppErrorCode,
  AppEventMethod,
  AppFrame,
  AppMethod,
  AskOpenedEvent,
  AskResolvedEvent,
  AskResult,
  AsksListParams,
  AsksListResult,
  AsksOpenParams,
  AsksRespondParams,
  ChannelCreatedEvent,
  ChannelResult,
  ChannelSnapshotEvent,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelSyncedEvent,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelUnsubscribeParams,
  ConversationResult,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsUpdateParams,
  ConversationUpdatedEvent,
  EmployeePatch,
  EmployeeResult,
  EmployeesCreateParams,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesUpdateParams,
  HarnessRegisterParams,
  HarnessRegisterResult,
  HarnessReportParams,
  HelloParams,
  JsonRpcNotification,
  JsonRpcRequest,
  JsonRpcResponse,
  MessageCreatedEvent,
  MessageResult,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  OkResult,
  ProtocolVersionMismatch,
  RequestId,
  RpcError,
  TurnInterruptRequestedEvent,
  TurnsInterruptParams,
  WelcomeResult,
} from "./wire";

/**
 * Registry of every app-protocol schema, consumed by
 * `packages/contracts/scripts/gen-schemas.ts` to render the generated JSON
 * Schema artifact (registries of other protocols register alongside it in
 * `GENERATED_DOCS` there).
 */
export const appProtocolSchemas = {
  RequestId,
  JsonRpcRequest,
  JsonRpcNotification,
  JsonRpcResponse,
  AppFrame,
  AppErrorCode,
  ProtocolVersionMismatch,
  RpcError,
  AppMethod,
  AppEventMethod,
  HelloParams,
  WelcomeResult,
  Employee,
  EmployeeStatus,
  RespondTo,
  EmployeePatch,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesCreateParams,
  EmployeesUpdateParams,
  EmployeeResult,
  AppChannel,
  ChannelKind,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelResult,
  Conversation,
  ConversationState,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsUpdateParams,
  ConversationResult,
  ChannelMessage,
  AppMessage,
  AuthorKind,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  MessageResult,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelUnsubscribeParams,
  OkResult,
  Ask,
  AskState,
  PendingTurn,
  EngineHostState,
  EngineHostStatus,
  HarnessRegisterParams,
  HarnessRegisterResult,
  HarnessReportParams,
  AsksOpenParams,
  AskResult,
  AsksRespondParams,
  AsksListParams,
  AsksListResult,
  TurnsInterruptParams,
  MessageCreatedEvent,
  ChannelSnapshotEvent,
  ChannelSyncedEvent,
  ConversationUpdatedEvent,
  ChannelCreatedEvent,
  AskOpenedEvent,
  AskResolvedEvent,
  TurnInterruptRequestedEvent,
} satisfies Record<string, z.ZodType>;

export const appProtocol = {
  name: "app",
  version: APP_PROTOCOL_VERSION,
  schemas: appProtocolSchemas,
};
