import type { z } from "zod";
import {
  AgentDescriptor,
  AgentsCreateParams,
  AgentsCreateResult,
  AgentsDescribeParams,
  AgentsDescribeResult,
  AgentsListParams,
  AgentsListResult,
} from "../engine/agents";
import { ModelsListParams, ModelsListResult } from "../engine/models";
import { ChannelMessage } from "../index";
import {
  AppChannel,
  AppMessage,
  Ask,
  AskState,
  AuthorKind,
  ChannelKind,
  Conversation,
  ConversationState,
  Employee,
  EmployeeStatus,
  EngineHostState,
  EngineHostStatus,
  MessageAttachment,
  PendingTurn,
  RespondTo,
} from "./domain";
import { UpdateFeed, UpdateRelease } from "./update";
import { APP_PROTOCOL_VERSION } from "./version";
import {
  AppErrorCode,
  AppEventMethod,
  AppFrame,
  AppMethod,
  AskOpenedEvent,
  AskResolvedEvent,
  AskResult,
  AsksListParams,
  AsksListResult,
  AsksOpenParams,
  AsksRespondParams,
  AttachmentInput,
  AttachmentsGetParams,
  AttachmentsGetResult,
  ChannelCreatedEvent,
  ChannelRemovedEvent,
  ChannelResult,
  ChannelSnapshotEvent,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelSyncedEvent,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelUnsubscribeParams,
  ConversationModelRequestedEvent,
  ConversationResult,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsSetModelParams,
  ConversationsUpdateParams,
  ConversationUpdatedEvent,
  EmployeePatch,
  EmployeeRemovedEvent,
  EmployeeResult,
  EmployeesCreateParams,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesRemoveParams,
  EmployeesUpdateParams,
  EmployeeUpsertedEvent,
  HarnessRegisterParams,
  HarnessRegisterResult,
  HarnessReportParams,
  HarnessStatusReport,
  HelloParams,
  JsonRpcNotification,
  JsonRpcRequest,
  JsonRpcResponse,
  MessageCreatedEvent,
  MessageResult,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  OkResult,
  ProtocolVersionMismatch,
  RequestId,
  RpcError,
  StatusComponent,
  StatusComponentId,
  StatusComponentState,
  StatusMismatch,
  SystemStatusParams,
  SystemStatusResult,
  TurnInterruptRequestedEvent,
  TurnsInterruptParams,
  WelcomeResult,
} from "./wire";

/**
 * Registry of every app-protocol schema, consumed by
 * `packages/contracts/scripts/gen-schemas.ts` to render the generated JSON
 * Schema artifact (registries of other protocols register alongside it in
 * `GENERATED_DOCS` there).
 */
export const appProtocolSchemas = {
  RequestId,
  JsonRpcRequest,
  JsonRpcNotification,
  JsonRpcResponse,
  AppFrame,
  AppErrorCode,
  ProtocolVersionMismatch,
  RpcError,
  AppMethod,
  AppEventMethod,
  HelloParams,
  WelcomeResult,
  Employee,
  EmployeeStatus,
  RespondTo,
  EmployeePatch,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesCreateParams,
  EmployeesUpdateParams,
  EmployeesRemoveParams,
  EmployeeResult,
  AppChannel,
  ChannelKind,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelResult,
  Conversation,
  ConversationState,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsSetModelParams,
  ConversationsUpdateParams,
  ConversationResult,
  ChannelMessage,
  AppMessage,
  AuthorKind,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  MessageResult,
  AttachmentInput,
  MessageAttachment,
  AttachmentsGetParams,
  AttachmentsGetResult,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelUnsubscribeParams,
  OkResult,
  Ask,
  AskState,
  PendingTurn,
  EngineHostState,
  EngineHostStatus,
  HarnessRegisterParams,
  HarnessRegisterResult,
  HarnessReportParams,
  HarnessStatusReport,
  StatusComponent,
  StatusComponentId,
  StatusComponentState,
  StatusMismatch,
  SystemStatusParams,
  SystemStatusResult,
  AsksOpenParams,
  AskResult,
  AsksRespondParams,
  AsksListParams,
  AsksListResult,
  TurnsInterruptParams,
  MessageCreatedEvent,
  ChannelSnapshotEvent,
  ChannelSyncedEvent,
  ConversationUpdatedEvent,
  ChannelCreatedEvent,
  AskOpenedEvent,
  AskResolvedEvent,
  TurnInterruptRequestedEvent,
  ChannelRemovedEvent,
  EmployeeUpsertedEvent,
  EmployeeRemovedEvent,
  ConversationModelRequestedEvent,
  /* release / update feed (#35) */
  UpdateRelease,
  UpdateFeed,
  /* engine passthrough surfaces (app -> relay -> engine host) */
  AgentDescriptor,
  AgentsListParams,
  AgentsListResult,
  AgentsDescribeParams,
  AgentsDescribeResult,
  AgentsCreateParams,
  AgentsCreateResult,
  ModelsListParams,
  ModelsListResult,
} satisfies Record<string, z.ZodType>;

export const appProtocol = {
  name: "app",
  version: APP_PROTOCOL_VERSION,
  schemas: appProtocolSchemas,
};
