import type { z } from "zod";
import { ChannelMessage } from "../index";
import {
  AppChannel,
  AppMessage,
  AuthorKind,
  ChannelKind,
  Conversation,
  ConversationState,
  Employee,
  EmployeeStatus,
  RespondTo,
} from "./domain";
import { APP_PROTOCOL_VERSION } from "./version";
import {
  AppErrorCode,
  AppEventMethod,
  AppFrame,
  AppMethod,
  ChannelResult,
  ChannelSnapshotEvent,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelSyncedEvent,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelUnsubscribeParams,
  ConversationResult,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsUpdateParams,
  ConversationUpdatedEvent,
  EmployeePatch,
  EmployeeResult,
  EmployeesCreateParams,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesUpdateParams,
  HelloParams,
  JsonRpcNotification,
  JsonRpcRequest,
  JsonRpcResponse,
  MessageCreatedEvent,
  MessageResult,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  OkResult,
  ProtocolVersionMismatch,
  RequestId,
  RpcError,
  WelcomeResult,
} from "./wire";

/**
 * Registry of every app-protocol schema, consumed by
 * `packages/contracts/scripts/generate-json-schemas.ts` to render the
 * generated JSON Schema artifact. Issue #6 (engine protocol) reuses the same
 * generator once it lands — it registers its own map there.
 */
export const appProtocolSchemas = {
  RequestId,
  JsonRpcRequest,
  JsonRpcNotification,
  JsonRpcResponse,
  AppFrame,
  AppErrorCode,
  ProtocolVersionMismatch,
  RpcError,
  AppMethod,
  AppEventMethod,
  HelloParams,
  WelcomeResult,
  Employee,
  EmployeeStatus,
  RespondTo,
  EmployeePatch,
  EmployeesListParams,
  EmployeesListResult,
  EmployeesCreateParams,
  EmployeesUpdateParams,
  EmployeeResult,
  AppChannel,
  ChannelKind,
  ChannelsListParams,
  ChannelsListResult,
  ChannelsOpenDmParams,
  ChannelResult,
  Conversation,
  ConversationState,
  ConversationsListParams,
  ConversationsListResult,
  ConversationsOpenParams,
  ConversationsOpenResult,
  ConversationsUpdateParams,
  ConversationResult,
  ChannelMessage,
  AppMessage,
  AuthorKind,
  MessagesListParams,
  MessagesListResult,
  MessagesPostParams,
  MessageResult,
  ChannelSubscribeParams,
  ChannelSubscribeResult,
  ChannelUnsubscribeParams,
  OkResult,
  MessageCreatedEvent,
  ChannelSnapshotEvent,
  ChannelSyncedEvent,
  ConversationUpdatedEvent,
} satisfies Record<string, z.ZodType>;

export const appProtocol = {
  name: "app",
  version: APP_PROTOCOL_VERSION,
  schemas: appProtocolSchemas,
};
