import { z } from "zod";
import { ApprovalOutcome, EngineRequest } from "../engine/requests";
import {
  AppChannel,
  AppMessage,
  Ask,
  AskState,
  AuthorKind,
  Conversation,
  ConversationState,
  Employee,
  EmployeeStatus,
  EngineHostStatus,
  PendingTurn,
  RespondTo,
} from "./domain";
import { APP_PROTOCOL_VERSION } from "./version";

/**
 * Wire framing: JSON-RPC 2.0 over one WebSocket endpoint (`/ws`), the same
 * shape the reference desktop app (AGENTS.md "Learn from these projects")
 * uses between renderer and engine
 * (`apps/shared/src/json-rpc-gateway.ts`). The first frame on a socket must
 * be a `session.hello` request carrying the protocol version and the
 * per-install auth token; every other method is rejected until hello
 * succeeds.
 */

export const RequestId = z.union([z.string().min(1), z.int()]);
export type RequestId = z.infer<typeof RequestId>;

export const JsonRpcRequest = z.object({
  jsonrpc: z.literal("2.0"),
  id: RequestId,
  method: z.string().min(1),
  params: z.record(z.string(), z.unknown()).optional(),
});
export type JsonRpcRequest = z.infer<typeof JsonRpcRequest>;

export const JsonRpcNotification = z.object({
  jsonrpc: z.literal("2.0"),
  method: z.string().min(1),
  params: z.record(z.string(), z.unknown()).optional(),
});
export type JsonRpcNotification = z.infer<typeof JsonRpcNotification>;

/** Codes carried in `error.data.code` (JSON-RPC `error.code` stays numeric). */
export const AppErrorCode = z.enum([
  "unauthenticated",
  "protocol_version_mismatch",
  "invalid_params",
  "not_found",
  "forbidden",
  "conflict",
  "internal",
]);
export type AppErrorCode = z.infer<typeof AppErrorCode>;

/** `error.data` for `protocol_version_mismatch`: names the stale side. */
export const ProtocolVersionMismatch = z.object({
  code: z.literal("protocol_version_mismatch"),
  /** Which side is older and must be updated. */
  update: z.enum(["client", "server"]),
  clientVersion: z.int(),
  serverVersion: z.int(),
});
export type ProtocolVersionMismatch = z.infer<typeof ProtocolVersionMismatch>;

export const RpcError = z.object({
  code: z.int(),
  message: z.string(),
  data: z.unknown().optional(),
});
export type RpcError = z.infer<typeof RpcError>;

export const JsonRpcResponse = z.union([
  z.object({ jsonrpc: z.literal("2.0"), id: RequestId, result: z.unknown() }),
  z.object({ jsonrpc: z.literal("2.0"), id: RequestId, error: RpcError }),
]);
export type JsonRpcResponse = z.infer<typeof JsonRpcResponse>;

/** Any frame on the app socket. */
export const AppFrame = z.union([
  JsonRpcRequest,
  JsonRpcNotification,
  JsonRpcResponse,
]);
export type AppFrame = z.infer<typeof AppFrame>;

/* ------------------------------- methods ------------------------------- */

export const AppMethod = z.enum([
  "session.hello",
  "employees.list",
  "employees.create",
  "employees.update",
  "channels.list",
  "channels.openDm",
  "conversations.list",
  "conversations.open",
  "conversations.update",
  "messages.list",
  "messages.post",
  "channel.subscribe",
  "channel.unsubscribe",
  "harness.register",
  "harness.report",
  "asks.open",
  "asks.respond",
  "asks.list",
  "turns.interrupt",
]);
export type AppMethod = z.infer<typeof AppMethod>;

export const HelloParams = z.object({
  protocolVersion: z.int().min(1),
  /** Per-install token generated by the relay on first run. */
  token: z.string().min(1),
  client: z
    .object({ name: z.string().optional(), version: z.string().optional() })
    .optional(),
});
export type HelloParams = z.infer<typeof HelloParams>;

export const WelcomeResult = z.object({
  protocolVersion: z.int(),
  relayVersion: z.string(),
  /**
   * Process identity of this relay run (`replay_epoch` analog in the reference gateway). A
   * change across reconnects tells the client its seq watermarks describe a
   * numbering that may no longer exist — it must resync from a snapshot.
   */
  instanceId: z.string().min(1),
  /** Engine host presence, so a client can show it without a second round trip. */
  engineHost: EngineHostStatus,
});
export type WelcomeResult = z.infer<typeof WelcomeResult>;

export const EmployeesListParams = z.object({}).strict();
export const EmployeesListResult = z.object({ employees: z.array(Employee) });

export const EmployeePatch = z.object({
  name: z.string().min(1).optional(),
  role: z.string().optional(),
  status: EmployeeStatus.optional(),
  profile: z.string().optional(),
  model: z.string().optional(),
  now: z.string().optional(),
  instructions: z.string().optional(),
  respondTo: RespondTo.optional(),
});
export type EmployeePatch = z.infer<typeof EmployeePatch>;

export const EmployeesCreateParams = z.object({
  name: z.string().min(1),
  role: z.string().default(""),
  status: EmployeeStatus.default("offline"),
  profile: z.string().default(""),
  model: z.string().default(""),
  now: z.string().default(""),
  instructions: z.string().default(""),
  respondTo: RespondTo.default("me"),
});
export type EmployeesCreateParams = z.infer<typeof EmployeesCreateParams>;

export const EmployeesUpdateParams = z.object({
  id: z.string().min(1),
  ...EmployeePatch.shape,
});
export type EmployeesUpdateParams = z.infer<typeof EmployeesUpdateParams>;

export const EmployeeResult = z.object({ employee: Employee });

export const ChannelsListParams = z.object({}).strict();
export const ChannelsListResult = z.object({ channels: z.array(AppChannel) });

/** Get-or-create the DM channel with one employee. */
export const ChannelsOpenDmParams = z.object({ employeeId: z.string().min(1) });
export type ChannelsOpenDmParams = z.infer<typeof ChannelsOpenDmParams>;
export const ChannelResult = z.object({ channel: AppChannel });

export const ConversationsListParams = z.object({
  channelId: z.string().min(1).optional(),
  includeArchived: z.boolean().default(false),
});
export type ConversationsListParams = z.infer<typeof ConversationsListParams>;
export const ConversationsListResult = z.object({
  conversations: z.array(Conversation),
});

/**
 * Opens a thread in a channel with its root message; the returned
 * conversation is `idle` until the harness attaches `engineRef`.
 */
export const ConversationsOpenParams = z.object({
  channelId: z.string().min(1),
  text: z.string().min(1),
  title: z.string().default(""),
  authorId: z.string().min(1).default("user"),
});
export type ConversationsOpenParams = z.infer<typeof ConversationsOpenParams>;
export const ConversationsOpenResult = z.object({
  conversation: Conversation,
  rootMessage: AppMessage,
});

/** Harness-facing: attach `engineRef`, flip `state`, rename, archive. */
export const ConversationsUpdateParams = z.object({
  conversationId: z.string().min(1),
  title: z.string().optional(),
  archived: z.boolean().optional(),
  state: ConversationState.optional(),
  engineRef: z.string().min(1).optional(),
});
export type ConversationsUpdateParams = z.infer<
  typeof ConversationsUpdateParams
>;
export const ConversationResult = z.object({ conversation: Conversation });

/**
 * History read. Without `afterSeq` returns the channel's messages (the last
 * `limit` when `limit` is set); with `afterSeq` returns the first `limit`
 * messages with `seq > afterSeq` — the same range replay pushes on resubscribe.
 */
export const MessagesListParams = z.object({
  channelId: z.string().min(1),
  afterSeq: z.int().min(0).optional(),
  limit: z.int().min(1).optional(),
});
export type MessagesListParams = z.infer<typeof MessagesListParams>;
export const MessagesListResult = z.object({
  messages: z.array(AppMessage),
  lastSeq: z.int().min(0),
});

export const MessagesPostParams = z.object({
  channelId: z.string().min(1),
  conversationId: z.string().min(1).optional(),
  text: z.string(),
  authorId: z.string().min(1).default("user"),
  authorKind: AuthorKind.default("user"),
});
export type MessagesPostParams = z.infer<typeof MessagesPostParams>;
export const MessageResult = z.object({ message: AppMessage });

/**
 * Resumable subscription (T3 Code `afterSequence` pattern, see
 * `docs/internals` + `apps/server/src/ws.ts`): without `afterSeq` the relay
 * sends a `channel.snapshot` notification; with it, the relay replays every
 * `message.created` newer than the cursor. A cursor ahead of the channel's
 * `lastSeq` is invalid and falls back to a snapshot. A `channel.synced`
 * notification always terminates the catch-up window and precedes live events.
 */
export const ChannelSubscribeParams = z.object({
  channelId: z.string().min(1),
  afterSeq: z.int().min(0).optional(),
});
export type ChannelSubscribeParams = z.infer<typeof ChannelSubscribeParams>;
export const ChannelSubscribeResult = z.object({
  channelId: z.string().min(1),
  lastSeq: z.int().min(0),
});

export const ChannelUnsubscribeParams = z.object({
  channelId: z.string().min(1),
});
export const OkResult = z.object({ ok: z.literal(true) });

/* ------------------------- harness + asks (#26) ------------------------- */

/**
 * Registers the calling connection as the engine host. The host is the only
 * writer allowed to attach `engineRef`/`state` on conversations, post
 * non-`user` messages, and open asks. A second concurrent registration is
 * refused with `conflict` — the relay has exactly one engine host. The result
 * returns `pending`: conversations whose newest message is a user message
 * (turns the engine still owes), so a restarted host catches up.
 */
export const HarnessRegisterParams = z.object({}).strict();
export const HarnessRegisterResult = z.object({
  hostId: z.string().min(1),
  pending: z.array(PendingTurn),
});

/** Host-only heartbeat of supervised engine state → welcome.engineHost. */
export const HarnessReportParams = z.object({
  engine: z.object({
    state: z.enum(["starting", "running", "restarting", "failed", "stopped"]),
    detail: z.string().optional(),
  }),
});

/** Host-only: surface an engine `request.opened` to the user. */
export const AsksOpenParams = z.object({
  channelId: z.string().min(1),
  conversationId: z.string().min(1),
  turnId: z.string().min(1),
  requestId: z.string().min(1),
  request: EngineRequest,
});
export type AsksOpenParams = z.infer<typeof AsksOpenParams>;
export const AskResult = z.object({ ask: Ask });

export const AsksRespondParams = z.object({
  askId: z.string().min(1),
  outcome: ApprovalOutcome,
  answer: z.string().optional(),
});
export type AsksRespondParams = z.infer<typeof AsksRespondParams>;

export const AsksListParams = z.object({
  channelId: z.string().min(1).optional(),
  conversationId: z.string().min(1).optional(),
  state: AskState.optional(),
});
export type AsksListParams = z.infer<typeof AsksListParams>;
export const AsksListResult = z.object({ asks: z.array(Ask) });

/** Any client: request an interrupt of the conversation's running turn. */
export const TurnsInterruptParams = z.object({
  conversationId: z.string().min(1),
});
export type TurnsInterruptParams = z.infer<typeof TurnsInterruptParams>;

/* -------------------------------- events ------------------------------- */

export const AppEventMethod = z.enum([
  "message.created",
  "channel.snapshot",
  "channel.synced",
  "conversation.updated",
  "channel.created",
  "ask.opened",
  "ask.resolved",
  "turn.interruptRequested",
]);
export type AppEventMethod = z.infer<typeof AppEventMethod>;

export const MessageCreatedEvent = z.object({
  channelId: z.string().min(1),
  message: AppMessage,
});
export type MessageCreatedEvent = z.infer<typeof MessageCreatedEvent>;

export const ChannelSnapshotEvent = z.object({
  channelId: z.string().min(1),
  messages: z.array(AppMessage),
  lastSeq: z.int().min(0),
});
export type ChannelSnapshotEvent = z.infer<typeof ChannelSnapshotEvent>;

/** Catch-up done: replay/snapshot delivered, live events follow. */
export const ChannelSyncedEvent = z.object({
  channelId: z.string().min(1),
  lastSeq: z.int().min(0),
});
export type ChannelSyncedEvent = z.infer<typeof ChannelSyncedEvent>;

export const ConversationUpdatedEvent = z.object({
  channelId: z.string().min(1),
  conversation: Conversation,
});
export type ConversationUpdatedEvent = z.infer<typeof ConversationUpdatedEvent>;

/** Broadcast to every helloed peer — a client learns of new channels live. */
export const ChannelCreatedEvent = z.object({ channel: AppChannel });
export type ChannelCreatedEvent = z.infer<typeof ChannelCreatedEvent>;

export const AskOpenedEvent = z.object({
  channelId: z.string().min(1),
  ask: Ask,
});
export type AskOpenedEvent = z.infer<typeof AskOpenedEvent>;

export const AskResolvedEvent = z.object({
  channelId: z.string().min(1),
  ask: Ask,
});
export type AskResolvedEvent = z.infer<typeof AskResolvedEvent>;

/**
 * A client asked for the conversation's running turn to be interrupted; the
 * registered engine host relays it to the engine as `interrupt`.
 */
export const TurnInterruptRequestedEvent = z.object({
  channelId: z.string().min(1),
  conversationId: z.string().min(1),
});
export type TurnInterruptRequestedEvent = z.infer<
  typeof TurnInterruptRequestedEvent
>;

export { APP_PROTOCOL_VERSION };
